/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emanuelsolanomanfredgonzalezucrtarea2;

import domain.Vehicle;
import file.VehicleFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Max
 */
public class Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        lbl_error.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfd_Serie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfd_Name = new javax.swing.JTextField();
        tfd_age = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        btn_UpDate = new javax.swing.JButton();
        btn_backUpDate = new javax.swing.JButton();
        cb_american = new javax.swing.JComboBox();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Buscar vehículo por numero de serie");

        jLabel2.setText("Nombre");

        jLabel4.setText("Año");

        jLabel5.setText("Americano");

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_UpDate.setText("Actualizar");
        btn_UpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpDateActionPerformed(evt);
            }
        });

        btn_backUpDate.setText("Atras");
        btn_backUpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backUpDateActionPerformed(evt);
            }
        });

        cb_american.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        lbl_error.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_backUpDate)
                        .addGap(71, 71, 71)
                        .addComponent(btn_UpDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_american, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfd_Serie)
                            .addComponent(tfd_Name)
                            .addComponent(tfd_age)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tfd_Serie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfd_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfd_age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_american, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_UpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_backUpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //method to search the single car
    public void searchCar(int serie) throws IOException{
        
        File file = new File("./vehicle.dat");
        VehicleFile vehicleFile = new VehicleFile(file);
        Vehicle car = new Vehicle();
        ArrayList<Vehicle> myArrayList = vehicleFile.getVehicleList();
        
        for(int i=0;i<myArrayList.size();i++){
            vehicleFile.cerrar();
            car = myArrayList.get(i);
            if(car.getSeries()==serie){
                vehicleFile.cerrar();
                tfd_Name.setText(car.getName());
                tfd_age.setText(""+car.getAge());
                cb_american.setSelectedItem(Boolean.toString(car.isAmerican()));
                lbl_error.setVisible(false);
                
            }else{
                lbl_error.setText("La serie ingresada no corresponde a ningún automovil");
                lbl_error.setVisible(true);
                
            }
        }
        
        vehicleFile.cerrar();
        
    }
    
    private void btn_backUpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backUpDateActionPerformed
        Principal prin = new Principal();
        
        prin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backUpDateActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {
            if(tfd_Serie.getText().equals("")){
            lbl_error.setVisible(true);
            lbl_error.setText("Por favor ingrese una serie");
        }else{
            lbl_error.setVisible(false);
            searchCar(Integer.parseInt(tfd_Serie.getText()));
            }
        } catch (IOException e) {
            System.err.println("The vehicle can't be in the file");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_UpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpDateActionPerformed
        // TODO add your handling code here
        
        if(tfd_Serie.getText().equals("")){
            lbl_error.setVisible(true);
            lbl_error.setText("Por favor ingrese una serie");
        }else{
            lbl_error.setVisible(false);
        int series = Integer.parseInt(tfd_Serie.getText());
        String name =tfd_Name.getText();
        int Age = Integer.parseInt(tfd_age.getText());
        boolean america= Boolean.parseBoolean(cb_american.getSelectedItem().toString());
        float Kilo = 0;
        try {
            File file = new File("./vehicle.dat");
            VehicleFile vehicleFile = new VehicleFile(file);
            Vehicle car = new Vehicle();
        ArrayList<Vehicle> myArrayList = vehicleFile.getVehicleList();
        for(int i=0;i<myArrayList.size();i++){
            car = myArrayList.get(i);
            if(car.getSeries()==series){
               Kilo=car.getMileage();
            }
        }
        Vehicle carNew = new Vehicle(name, Age, Kilo, america, series);
        vehicleFile.updateCar(carNew, series);
        vehicleFile.cerrar();
        } catch (IOException ex) {
            System.err.println("The vehicle can't be in the file");
        }
        tfd_Name.setText("");
        tfd_Serie.setText("");
        tfd_age.setText("");
        tfd_Serie.requestFocus();
        }
    }//GEN-LAST:event_btn_UpDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_UpDate;
    private javax.swing.JButton btn_backUpDate;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cb_american;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTextField tfd_Name;
    private javax.swing.JTextField tfd_Serie;
    private javax.swing.JTextField tfd_age;
    // End of variables declaration//GEN-END:variables
}
