/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emanuelsolanomanfredgonzalezucrtarea2;

/**
 *
 * @author Max
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_InterfaceInput = new javax.swing.JButton();
        btn_InterfaceUpDate = new javax.swing.JButton();
        btn_InterfaceDelete = new javax.swing.JButton();
        btn_InterfaceList = new javax.swing.JButton();
        btn_InterfaceExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Vehículo");

        btn_InterfaceInput.setText("Insertar");
        btn_InterfaceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InterfaceInputActionPerformed(evt);
            }
        });

        btn_InterfaceUpDate.setText("Actualizar");
        btn_InterfaceUpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InterfaceUpDateActionPerformed(evt);
            }
        });

        btn_InterfaceDelete.setText("Borrar");
        btn_InterfaceDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InterfaceDeleteActionPerformed(evt);
            }
        });

        btn_InterfaceList.setText("Listado");
        btn_InterfaceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InterfaceListActionPerformed(evt);
            }
        });

        btn_InterfaceExit.setText("Salir");
        btn_InterfaceExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InterfaceExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_InterfaceUpDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_InterfaceInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_InterfaceDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_InterfaceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_InterfaceExit)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_InterfaceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_InterfaceUpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_InterfaceDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_InterfaceList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_InterfaceExit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InterfaceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InterfaceInputActionPerformed
        // TODO add your handling code here:
        Insertar is = new Insertar();
        is.setVisible(true);
        is.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_InterfaceInputActionPerformed

    private void btn_InterfaceExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InterfaceExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_InterfaceExitActionPerformed

    private void btn_InterfaceUpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InterfaceUpDateActionPerformed
        // TODO add your handling code here:
        Actualizar at= new Actualizar();
        at.setVisible(true);
        at.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_InterfaceUpDateActionPerformed

    private void btn_InterfaceDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InterfaceDeleteActionPerformed
        // TODO add your handling code here:
        Borrar br = new Borrar();
        br.setVisible(true);
        br.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_InterfaceDeleteActionPerformed

    private void btn_InterfaceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InterfaceListActionPerformed
        // TODO add your handling code here:
        Listado li = new Listado();
        li.setVisible(true);
        li.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_InterfaceListActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_InterfaceDelete;
    private javax.swing.JButton btn_InterfaceExit;
    private javax.swing.JButton btn_InterfaceInput;
    private javax.swing.JButton btn_InterfaceList;
    private javax.swing.JButton btn_InterfaceUpDate;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
